kind: secret
name: dockerconfig
get:
  path: travel-registry
  name: .dockerconfigjson

---
kind: pipeline
name: Nuget packages
        
trigger:
  branch:
    - main
  event:
    - push
    
steps:
- name: run ReSharper
  image:  mcr.microsoft.com/dotnet/sdk:8.0
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

  commands:
    - dotnet new tool-manifest
    - dotnet tool install JetBrains.ReSharper.GlobalTools
    - dotnet jb inspectcode HappyTravel.BaseConnector.StaticDataManager.sln --build --severity=error --verbosity=error -o=/dev/null

- name: Build packages
  image: mcr.microsoft.com/dotnet/sdk:8.0
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
    - dotnet build -c Release
    - dotnet pack -c Release -o out
    - dotnet nuget push "./out/*.nupkg" --skip-duplicate --no-symbols  -s github

- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    username: delivery
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status: [success, failure]
image_pull_secrets:
- dockerconfig
