name: linux-x64 Test

on:
  push:
    branches: [ master ]

jobs:
  ubuntu-test:
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Test .NET 6
      run: dotnet test -v quiet -f net6.0 --logger "console;verbosity=detailed" --nologo /nologo
    - name: Test .NET 5
      run: dotnet test -v quiet -f net5.0 --logger "console;verbosity=detailed" --nologo /nologo
    - name: Test .NET Core 3.1
      run: dotnet test -v quiet -f netcoreapp3.1 --logger "console;verbosity=detailed" --nologo /nologo