name: linux-x64 Test

on:
  push:
    branches: [ master ]

jobs:
  ubuntu-test:
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      matrix:
        os: [ 'ubuntu-18.04', 'ubuntu-20.04' ]
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
            3.1.x
            5.x
            6.x
    - name: Test .NET 6
      run: dotnet test -v quiet -f net6.0 --logger "console;verbosity=detailed" --nologo /nologo
    - name: Test .NET 5
      run: dotnet test -v quiet -f net5.0 --logger "console;verbosity=detailed" --nologo /nologo
    - name: Test .NET Core 3.1
      run: dotnet test -v quiet -f netcoreapp3.1 --logger "console;verbosity=detailed" --nologo /nologo